### PR TITLE
Added Android support

### PR DESCRIPTION
**Pull request by richardgill**
#1

This works for me. I've removed `-ios` in a bunch of places. It would be good republish into npm with the new name. 

Thanks,

Richard

### CODE REVIEW

**Comment by kagalenitin** [comment]
any update on this one?

**Comment by kagalenitin** [comment]
Thanks guys. very good!!

**Comment by brunolemos** [comment]
Doesn't seem to be working on android anymore :(
#9

**Comment by negativetwelve** [comment]
Hi @brunolemos, please open a new issue with the specific version of react-native that is no longer working. That way we can track the new issue and make sure it gets solved.

**Comment by brunolemos** [comment]
@negativetwelve sorry, it seems it does work. I just had a hard time making the shake gesture in the emulator.

**Comment by negativetwelve** [comment]
no problem, thanks for letting us know!

**Pull request merged**
